src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: "email", message: "Cet email est deja utilise")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message: "Veuillez renseigner ce champ")]
    #[Assert\Email(message: "Veuillez entrer un email valide")]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]    
    #[Assert\Length(min: 5, minMessage: "Votre mot de passe est trop court")]
    #[Assert\NotBlank(message: "Veuillez renseigner ce champ")]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez renseigner ce champ")]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez renseigner ce champ")]
    private ?string $lastname = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Question::class, orphanRemoval: true)]
    private Collection $questions;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\Column(length: 255)]
    private string $avatar;

    #[Assert\Length(min: 5, minMessage: "Votre mot de passe est trop court")]
    private ?string $newPassword = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Vote::class, orphanRemoval: true)]
    private Collection $votes;

    public function getNewPassword(): ?string
    {
        return $this->newPassword;
    }

    public function setNewPassword(string $newPassword): static
    {
        $this->newPassword = $newPassword;

        return $this;
    }

    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullname(): string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): static
    {
        if (!$this->questions->contains($question)) {
            $this->questions->add($question);
            $question->setAuthor($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): static
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getAuthor() === $this) {
                $question->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getAvatar(): string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): static
    {
        if (!$this->votes->contains($vote)) {
            $this->votes->add($vote);
            $vote->setAuthor($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): static
    {
        if ($this->votes->removeElement($vote)) {
            // set the owning side to null (unless already changed)
            if ($vote->getAuthor() === $this) {
                $vote->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname', TextType::class, [
                'label' => '* Prenom',
                'required' => false
            ])
            ->add('lastname', TextType::class, [
                'label' => '* Prenom',
                'required' => false
            ])
            ->add('email', EmailType::class, [
                'label' => '* Email',
                'required' => false
            ])
            ->add('password', PasswordType::class, [
                'label' => '* Mot de passe',
                'required' => false
            ])
            ->add('pictureFile', FileType::class, [
                'required' => false,
                'mapped' => false,
                'constraints' => [
                    new Image([
                        'mimeTypesMessage' => 'Veuillez uploader une image',
                        'maxSize' => '1M',
                        'maxSizeMessage' => 'Votre image fait {{size}} {{suffix}}. La limite est de {{limit}} {{suffix}}.'
                    ])
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Services\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/user/profile', name: 'user_')]
class UserController extends AbstractController
{
    
    #[Route('/', name: 'current_profile')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function diplayCurrentUserProfile(Request $request, UserPasswordHasherInterface $hasher, EntityManagerInterface $em, FileUploader $fileUploader): Response
    {
        /** @var User */
        $currentUser = $this->getUser();
        $userForm = $this->createForm(UserType::class, $currentUser);
        $userForm->remove('password');
        $userForm->add('newPassword', PasswordType::class, [
            'label' => 'Nouveau mot de passe',
            'required' => false
        ]);
        $userForm->handleRequest($request);

        if($userForm->isSubmitted() && $userForm->isValid()) {
            $newPassord = $currentUser->getNewPassword();
            if($newPassord) {
                $hash = $hasher->hashPassword($currentUser, $newPassord);
                $currentUser->setPassword($hash);
            }

            $picture = $userForm->get('pictureFile')->getData();
            if($picture) {
                $currentUser->setAvatar($fileUploader->uploadProfileImage($picture, $currentUser->getAvatar()));
            }

            $em->flush();
            $this->addFlash('success', 'Modifications sauvegardees');
        }

        return $this->render('user/current-user-profile.html.twig', ['form' => $userForm]);
    }

    #[Route('/questions', name: 'show_questions')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function showQuestions(): Response
    {
        return $this->render('user/show-questions.html.twig');
    }

    #[Route('/comments', name: 'show_comments')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function showComments(): Response
    {
        return $this->render('user/show-comments.html.twig');
    }

    #[Route("/{id}", name: 'profile')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function diplayUserProfile(User $user): Response
    {
        $currentUser = $this->getUser();
        if($user == $currentUser) {
            return $this->redirectToRoute('user_current_profile');
        }
        
        return $this->render('user/user-profile.html.twig', ['user' => $user]);
    }

}

templates/user/current-user-profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{app.user.fullname}} | Profile{% endblock %}

{% block body %}
    <div class="block">
        <h2 class="pb-30">Page de profil</h2>
        {{form_start(form)}}
            {{form_rest(form)}}
            <button class="btn btn-primary">Sauvegarder</button>
        {{form_end(form)}}
    </div>

{% endblock %}

templates/user/show-comments.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{app.user.fullname}} | Reponses{% endblock %}

{% block body %}
    <div class="block mb-20">
        <h3 class="pb-30">Mes reponses</h3>
        <ul>
            {% for comment in app.user.comments %}
                <a href="{{path('question_show', {id: comment.question.id})}}">
                    <li class="pb-30">{{comment.content | slice(0, 50)}} {% if comment.content | length >= 51 %}
                        ...
                    {% endif %}</li>
                </a>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/user/show-questions.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{app.user.fullname}} | Questions{% endblock %}

{% block body %}
    <div class="block mb-20">
        <h3 class="pb-30">Mes questions</h3>
        <ul>
            {% for question in app.user.questions %}
                <a href="{{path('question_show', {id: question.id})}}">
                    <li class="pb-30">{{question.title}}</li>
                </a>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/user/user-profile.html.twig
{% extends "base.html.twig" %}

{% block title %}
    {{ user.fullname }} | Profile
{% endblock title %}

{% block body %}
    <div class="block mb-20">
        <h2 class="pb-30">{{ user.fullname }}</h2>
        <div class="d-flex flex-row-nowrap">
            <img src="{{ asset(user.avatar) }}" alt="Profil Picture" class="mr-10 avatar-lg">
            <ul>
                <li class="mb-10">
                    <strong class="mr-10">Prenom: </strong>{{user.firstname}}
                </li>
                <li class="mb-10">
                    <strong class="mr-10">Nom: </strong>{{user.lastname}}
                </li>
                <li class="mb-10">
                    <strong class="mr-10">Email: </strong>{{user.email}}
                </li>
            </ul>
        </div>
    </div>

    <div class="block mb-20">
        <h3 class="pb-30">Ces questions</h3>
        <ul>
            {% for question in user.questions %}
                <a href="{{ path('question_show', {id: question.id}) }}">
                    <li class="pb-30">{{ question.title }}</li>
                </a>
            {% endfor %}
        </ul>
    </div>

    <div class="block mb-20">
        <h3 class="pb-30">Ces reponses</h3>
        <ul>
            {% for comment in user.comments %}
                <li class="pb-30">{{ comment.content | slice(0, 50) }} {% if comment.content |length >= 51 %}
                  ...
                {% endif %} </li>
            {% endfor %}
        </ul>
    </div>
{% endblock body %}